### ISSUE TITLE
Example fig installation

### ISSUE THREAD

**Issue by aboe76** [samos123/docker-tutum-drupal#2]
Hi Samos,

Here is an example of your docker drupal in combination with the default docker mysql
to be used with fig. Hope you will add this to your readme file.

Just create fig.yml and run fig up and everything should be starting automatically.

fig.yml file:
```
drupal:
  image: samos123/drupal
  links:
    - db:db
  ports:
    - "80:80"
  environment:
    DB_USER: root
    DB_PASS: supersecretpassword

db:
  image: mysql
  ports:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: supersecretpassword
```
